// Generated by nitro
import type { Serialize, Simplify } from "nitro/types";
declare module "nitro/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/register.post').default>>>>
    }
    '/api/messages/:sessionId': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/messages/[sessionId].post').default>>>>
    }
    '/api/sessions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sessions/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sessions/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sessions/[id].put').default>>>>
    }
    '/api/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sessions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sessions/index.post').default>>>>
    }
    '/api/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/settings/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/settings/index.put').default>>>>
    }
  }
}
export {}